@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Story" as Story [[/concept/story/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Persona" as Persona [[/concept/persona/#ontology]]
class "Outcome" as Outcome [[/concept/outcome/#ontology]]
class "OutcomeStereotype" as OutcomeStereotype [[/concept/outcome/outcome-stereotype/#ontology]]
class "Concept" as Concept [[/concept/concept/#ontology]]
class "ConceptVocabulary" as ConceptVocabulary [[/concept/concept/concept-vocabulary/#ontology]]
class "Term" as Term [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm [[/concept/term/business-term/#ontology]]
class "TechnicalTerm" as TechnicalTerm [[/concept/term/technical-term/#ontology]]
class "WorkflowDefinition" as WorkflowDefinition [[/concept/workflow/#ontology]]
class "StoryConceptRelationship" as StoryConceptRelationship [[/concept/concept/story-concept-relationship/#ontology]]
class "StoryImplementation" as StoryImplementation [[/concept/story/implementation/#ontology]]
class "StoryTestScenario" as StoryTestScenario [[/concept/story/test-scenarios/#ontology]]

' Term specializations
Term <|-- BusinessTerm
Term <|-- TechnicalTerm

' Other resources point to UseCase (typical KG modeling style)
Story "0..*" --> "1" UseCase : :useCase

' Use Case Tree structure
UseCase "0..*" --> "0..1" UseCase : :isPartOf
UseCase "0..*" --> "0..*" UseCase : :isUsedIn

' Outcome has optional stereotype
Outcome "0..1" --> "1" OutcomeStereotype : outcome:stereotype

' Story structure
Story --> Persona : :playedBy
Story --> Outcome : :contributesTo

' Concept vocabulary ownership
UseCase "1" *-- "0..*" ConceptVocabulary : :conceptVocabulary
ConceptVocabulary "1" o-- "0..*" Concept : skos:inScheme

' Concept usage
Story "0..*" --> "1" StoryConceptRelationship : :storyConcept
StoryConceptRelationship --> Concept : :concept
Concept "1" *-- "1..*" Term : :term
Concept "0..1" --> "1" BusinessTerm : :labelTerm

' Implementation
Story "1" --> "0..*" StoryImplementation : :implementation

' Test scenarios
Story "1" --> "0..*" StoryTestScenario : :testScenario

' Workflow participation
WorkflowDefinition --> Story : :steps

@enduml

