@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "UseCaseStereotype" as UseCaseStereotype [[/concept/use-case/use-case-stereotype/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "WorkflowDefinition" as WorkflowDefinition [[/concept/workflow/#ontology]]
class "Outcome" as Outcome [[/concept/outcome/#ontology]]
class "OutcomeStereotype" as OutcomeStereotype [[/concept/outcome/outcome-stereotype/#ontology]]
class "OutcomeRelationship" as OutcomeRelationship [[/concept/outcome/outcome-relationship/#ontology]]
class "Concept" as Concept [[/concept/concept/#ontology]]
class "ConceptVocabulary" as ConceptVocabulary [[/concept/concept/concept-vocabulary/#ontology]]
class "ConceptManifestation" as ConceptManifestation [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm [[/concept/term/business-term/#ontology]]
class "TechnicalManifestation" as TechnicalManifestation [[/concept/term/technical-term/#ontology]]
class "Persona" as Persona [[/concept/persona/#ontology]]
class "StoryConceptRelationship" as StoryConceptRelationship [[/concept/concept/story-concept-relationship/#ontology]]

' Ownership / composition (part-of)
UseCase "1" *-- "0..*" Story : owns
UseCase "1" *-- "0..*" WorkflowDefinition : owns
UseCase "0..1" *-- "0..*" UseCase : is-part-of
UseCase "0..*" o-- "0..*" UseCase : is-used-in
Concept "1" *-- "0..*" ConceptManifestation : owns

' Inheritance
ConceptManifestation <|-- BusinessTerm
ConceptManifestation <|-- TechnicalManifestation

' Relationships
UseCase "0..1" --> "1" UseCaseStereotype : hasStereotype
Outcome "0..1" --> "1" OutcomeStereotype : hasStereotype
UseCase "0..*" --> "0..*" OutcomeRelationship : outcomeLink
OutcomeRelationship --> Outcome : targetOutcome
UseCase "0..*" --> "0..*" ConceptVocabulary : references/owns
ConceptVocabulary "1" o-- "0..*" Concept : contains

' Usage
Story --> Persona : story:playedBy
Story --> Outcome : story:contributesTo
Story --> StoryConceptRelationship : story:relatedConcept
StoryConceptRelationship --> Concept: story:concept
WorkflowDefinition --> Story : workflow:firstStep

@enduml

