@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Outcome" as Outcome [[/concept/outcome/index.md#ontology]]
class "OutcomeRelationship" as OutcomeRelationship [[/concept/outcome/outcome-relationship/#ontology]]

' Links
OutcomeRelationship "0..*" --> "1" UseCase : :useCase
OutcomeRelationship "0..*" --> "1" Outcome : :targetOutcome

@enduml

