@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "ConceptManifestation" as ConceptManifestation [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm [[/concept/term/business-term/#ontology]]
class "Concept" as Concept [[/concept/concept/#ontology]]

' Inheritance
ConceptManifestation <|-- BusinessTerm

' Ownership
Concept "1" *-- "0..*" BusinessTerm : :hasManifestation

@enduml
