@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Term" as Term [[/concept/term/#ontology-facts]]
class "TechnicalTerm" as TechnicalTerm [[/concept/term/technical-term/#ontology-facts]]
class "Concept" as Concept [[/concept/concept/#ontology-facts]]

' Inheritance
Term <|-- TechnicalTerm

' Ownership
Concept "1" *-- "1..*" TechnicalTerm : owns

@enduml

