@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Concept" as Concept [[/concept/concept/#ontology]]
class "Term" as Term [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm
class "TechnicalTerm" as TechnicalTerm
class "ConceptVocabulary" as ConceptVocabulary
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "StoryConceptRelationship" as StoryConceptRelationship

' Term specializations
Term <|-- BusinessTerm
Term <|-- TechnicalTerm

' Terms
Concept "1" *-- "1..*" Term : :term
Concept "0..1" --> "1" BusinessTerm : :labelTerm

' Vocabularies
ConceptVocabulary "1" o-- "0..*" Concept : skos:inScheme
ConceptVocabulary "0..*" --> "1" UseCase : :useCase

' Usage
Story "0..*" --> "1" StoryConceptRelationship : :storyConcept
StoryConceptRelationship --> Concept : :concept

@enduml

