@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Concept" as Concept [[/concept/concept/#ontology]]
class "ConceptVocabulary" as ConceptVocabulary [[/concept/concept/concept-vocabulary/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "StoryConceptRelationship" as StoryConceptRelationship [[/concept/concept/story-concept-relationship/#ontology]]

' Concepts belong to a Concept Vocabulary
ConceptVocabulary "1" o-- "0..*" Concept : skos:inScheme

' Use Case owns Concept Vocabularies
UseCase "1" *-- "0..*" ConceptVocabulary : :conceptVocabulary

' Stories use concepts
Story "0..*" --> "1" StoryConceptRelationship : :storyConcept
StoryConceptRelationship --> Concept : :concept

@enduml
