@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Outcome" as Outcome [[/concept/outcome/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "OutcomeRelationship" as OutcomeRelationship

' Outcome linkage (relationship-object)
OutcomeRelationship "0..*" --> "1" UseCase : :useCase
OutcomeRelationship --> Outcome : :targetOutcome

' Stories reference outcomes as "why"
Story --> Outcome : :contributesTo

@enduml

