@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Term" as Term [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm [[/concept/term/business-term/#ontology]]
class "TechnicalTerm" as TechnicalTerm [[/concept/term/technical-term/#ontology]]
class "Concept" as Concept [[/concept/concept/#ontology]]
class "ConceptVocabulary" as ConceptVocabulary [[/concept/concept/concept-vocabulary/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]

' Term specializations
Term <|-- BusinessTerm
Term <|-- TechnicalTerm

' Ownership
Concept "1" *-- "1..*" Term : :term
Concept "0..1" --> "1" BusinessTerm : :labelTerm

' Context (terms live inside vocabularies used by use cases)
ConceptVocabulary "1" o-- "0..*" Concept : skos:inScheme
ConceptVocabulary "0..*" --> "1" UseCase : :useCase

' Use Case Tree structure
UseCase "0..*" --> "0..1" UseCase : :isPartOf
UseCase "0..*" --> "0..*" UseCase : :isUsedIn

@enduml

