@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "ConceptManifestation" as ConceptManifestation [[/concept/term/#ontology]]
class "TechnicalManifestation" as TechnicalManifestation [[/concept/term/technical-term/#ontology]]
class "Concept" as Concept [[/concept/concept/#ontology]]

' Inheritance
ConceptManifestation <|-- TechnicalManifestation

' Ownership
Concept "1" *-- "0..*" TechnicalManifestation : :hasManifestation

@enduml
