@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Story" as Story [[/concept/story/#ontology-facts]]
class "Concept" as Concept [[/concept/concept/#ontology-facts]]
class "StoryConceptRelationship" as StoryConceptRelationship [[/concept/concept/story-concept-relationship/#ontology-facts]]

' Usage
Story "0..*" *-- "1" StoryConceptRelationship : owns
StoryConceptRelationship "0..*" --> "1" Concept : concept

@enduml

