@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Persona" as Persona [[/concept/persona/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "PersonaTaxonomy" as PersonaTaxonomy

' Personas show up in stories ("playedBy") which are owned by a use case
Story --> Persona : :playedBy
Story "0..*" --> "1" UseCase : :useCase

' Personas belong to a PersonaTaxonomy (SKOS concept scheme)
Persona --> PersonaTaxonomy : skos:inScheme
PersonaTaxonomy "0..1" --> "1" UseCase : :useCase

' Persona inheritance (optional)
Persona --> Persona : :isSubPersonaOf

@enduml

