@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Persona" as Persona [[/concept/persona/#ontology]]
class "PersonaTaxonomy" as PersonaTaxonomy [[/concept/persona/persona-taxonomy/#ontology]]

' Taxonomy ownership
PersonaTaxonomy "0..1" --> "1" UseCase : :useCase

' Personas belong to taxonomy
Persona "0..*" --> "1" PersonaTaxonomy : skos:inScheme

@enduml
