@startuml
!include ../include/themes/light.puml
top to bottom direction
hide members

class "Concept" as Concept [[/concept/concept/#ontology]]
class "ConceptManifestation" as ConceptManifestation [[/concept/term/#ontology]]
class "BusinessTerm" as BusinessTerm [[/concept/term/business-term/#ontology]]
class "TechnicalManifestation" as TechnicalManifestation [[/concept/term/technical-term/#ontology]]
class "ConceptVocabulary" as ConceptVocabulary [[/concept/concept/concept-vocabulary/#ontology]]
class "UseCase" as UseCase [[/concept/use-case/#ontology]]
class "Story" as Story [[/concept/story/#ontology]]
class "StoryConceptRelationship" as StoryConceptRelationship [[/concept/concept/story-concept-relationship/#ontology]]

' Manifestation specializations
ConceptManifestation <|-- BusinessTerm
ConceptManifestation <|-- TechnicalManifestation

' Manifestations
Concept "1" *-- "0..*" ConceptManifestation : :hasManifestation
Concept "0..1" --> "1" BusinessTerm : :preferredBusinessTerm

' Vocabularies
ConceptVocabulary "1" o-- "0..*" Concept : skos:inScheme
ConceptVocabulary "0..*" --> "1" UseCase : :useCase

' Use Case Tree structure
UseCase "0..*" --> "0..1" UseCase : :isPartOf
UseCase "0..*" --> "0..*" UseCase : :isUsedIn

' Usage
Story "0..*" --> "1" StoryConceptRelationship : :storyConcept
StoryConceptRelationship --> Concept : :concept

@enduml
