title: Other
nav:
  - index.md
  - EKGF: https://ekgf.org
  - Principles: https://principles.ekgf.org
  - Maturity Model: https://maturity-model.ekgf.org
  - Use Case Tree Method: https://method.ekgf.org
  - author
