mkdocs-infra:
  - any:
      - changed-files:
          - Makefile
          - mkdocs.yml
          - docs-overrides/**
          - docs/assets/**
          - docs/stylesheets/**
          - docs/main.py
          - '**/CNAME'
          - .tool-versions
          - README.md

github-actions:
  - any:
      - changed-files:
          - .github/**

agnos-ai:
  - any:
      - changed-files:
          - 'agnos-*'
          - '*-agnos/**/*'
          - '*-agnos-ai/**/*'



