title: Objectives
nav:
  - know-what-the-business-wants.md
  - Bridge the Gap: bridge-the-gap.md
  - Manage Expectations: manage-expectations.md
  - Enable Reuse: enable-reuse.md
  - No boiling ocean: avoid-boiling-the-ocean.md
  - capture-knowledge.md
  - avoid-disruption.md
  - increase-quality.md
  - align-with-business-strategy.md
  - ...