name: Build Website

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Git repository
        uses: actions/checkout@v2.4.0
      -
        uses: actions/cache@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          key: ${{ github.ref }}
          path: .cache
      -
        name: Install all MkDocs dependencies
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          make docs-install-python-packages
      -
        name: Build Site
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          make docs-build
      -
        name: Deploy Site
        if: ${{ github.ref == 'refs/heads/main' }}
        run: make docs-deploy
